---
genome: /scratch/data_hg/male.hg19.fasta
features:
    dir_path: /scratch/data_hg/
    filenames:
        genomic_features: sorted_aggregate.bed.gz
        coords_only: coords_only.txt
        distinct_features: distinct_features.txt
output_dir: /tigress/kc31/outputs
...
