---
genome: /tigress/kc31/hg19/male.hg19.fasta
features:
    dir_path: /tigress/kc31/hg19_1ChIP
    filenames:
        genomic_features: CTCF_hg19_ChIP.bed.gz
        coords_only: coords_only.txt
        distinct_features: distinct_features.txt 
output_logs: /tigress/kc31/logs
output_models: /tigress/kc31/models
...
