---
#optimizer:
#    name: Adam
#    learning_rate: 1e-03
sampler:
    holdout_test:
        - chr8
        - chr9
    holdout_validate:
        - chr6
        - chr7
    optional_args:
        radius: 100
        window_size: 1001
        random_seed: 436
        mode: train
        sample_from: positive
model_controller:
    batch_size: 128
    n_epochs: 500
    n_train_batch_per_epoch: 2000
    n_total_validate: 5000
    optional_args:
        use_cuda: True
        data_parallel: False
    checkpoint:
        resume: False
...
