---
sampler:
    test_holdout:
        - 8
        - 9
    validation_holdout:
        - 6
        - 7
    random_seed: 127
    sequence_length: 1001
    center_bin_to_predict: 201
    default_threshold: 0.5
    mode: train
model_controller:
    batch_size: 64
    max_steps: 500000
    report_metrics_every_n_steps: 16000
    n_validation_samples: 3200
    optional_args:
        cpu_n_threads: 32
        use_cuda: True
        data_parallel: False
    checkpoint:
        resume: False
...
