---
ops: [train, evaluate]
model: {
    file: /home/kathy/models/deepsea.py,
    class: DeepSEA,
    sequence_length: 1000,
    n_classes_to_predict: 919,
    non_strand_specific: {
        use_module: True,
        mode: mean
    }
}
sampler: !obj:selene.samplers.IntervalsSampler {
    reference_sequence: !obj:selene.sequences.Genome {
            input_path: /data/home/ecofer/data/cardiac_deepsea/all_heart_data/mm9.fasta
            },
    features: !obj:selene.utils.load_features_list {
        input_path: /data/home/ecofer/data/cardiac_deepsea/all_heart_data/distinct_features.txt
    },
    target_path: /data/home/ecofer/data/cardiac_deepsea/all_heart_data/sorted_mm9_heart.bed.gz
    intervals_path: /data/home/ecofer/data/cardiac_deepsea/all_heart_data/intervals_only.txt,
    sequence_length: 1000,
    center_bin_to_predict: 200,
    test_holdout: [chr8, chr9],
    validation_holdout: [chr6, chr7],
    feature_thresholds: 0.5,
    seed: 127,
    mode: "train",
    save_datasets: [
        test
    ]
}
train_model: !obj:selene.TrainModel {
    batch_size: 64,
    max_steps: 500000,
    report_stats_every_n_steps: 16000,
    n_validation_samples: 32000,
    cpu_n_threads: 32,
    use_cuda: True,
    data_parallel: False,
    logging_verbosity: 2,
    output_dir: /data/home/ecofer/data/cardiac_deepsea/example_outputs
}
lr: 0.10
evaluate_on_test: True
save_datasets: True
...
