---
ops: [analyze]
model: {
    path: /mnt/home/kchen/Documents/kathy_fork/selene/variant_effect_prediction/models/expecto_deepsea/deepsea_beluga.py,
    class: Beluga,
    class_args: {
    },
    non_strand_specific: mean
}
analyze_sequences: !obj:selene_sdk.predict.AnalyzeSequences {
    sequence_length: 2000,
    batch_size: 64,
    use_cuda: True,
    data_parallel: True,
    trained_model_path: /mnt/home/kchen/Documents/kathy_fork/selene/variant_effect_prediction/models/expecto_deepsea/deepsea_beluga.pth,
    features: !obj:selene_sdk.utils.load_features_list {
        input_path: /mnt/home/kchen/Documents/kathy_fork/selene/variant_effect_prediction/models/expecto_deepsea/predictor_names.txt
    },
    write_mem_limit: 75000
}
variant_effect_prediction: {
    save_data: [diffs],
    output_format: hdf5,
}
random_seed: 999
...
